version: "3"

services:
  install:
    image: node:local
    command: npm install
    working_dir: /workspace
    volumes:
     - ./:/workspace

    build: 
      dockerfile: ./Dockerfile

  build:
    depends_on: 
      - install
    image: node:local
    command: npm run build
    working_dir: /workspace
    volumes:
     - ./:/workspace

    build: 
      dockerfile: ./Dockerfile


  heygen:
    depends_on: 
     - build
    image: node:local
    command: npm run start
    working_dir: /workspace
    volumes:
     - ./:/workspace

    ports:
      - 3000:3000

    build: 
      dockerfile: ./Dockerfile